[versions]
application = "8.0.2"
kotlin-android = "1.8.20"
androidCoreX = "1.8.0"
androidFragmentX = "1.5.7"
androidCompat = "1.4.1"
androidViewModelX = "2.6.1"
material = "1.5.0"
androidConstraint = "2.1.3"
retrofit = "2.9.0"
gson = "2.10.1"
gson-converter = "2.9.0"
hilt = "2.46.1"
inject = "1"
coroutine = "1.3.9"
coroutine-core = "1.7.3"
kakao = "2.15.0"
logging-interceptor = "4.11.0"
timber = "5.0.1"
junit = "4.13.2"
junit-ext = "1.1.5"
espresso = "3.5.1"
firebase-plugin = "4.3.15"
firebase-bom = "32.2.2"
glide = "4.15.1"
jodatime = "2.12.5"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analysis = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-dynamic-links = { group = "com.google.firebase", name = "firebase-dynamic-links-ktx" }
androidCoreX = { group = "androidx.core", name = "core-ktx", version.ref = "androidCoreX" }
androidCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidCompat" }
androidConstraint = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidConstraint" }
viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidViewModelX" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidFragmentX" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
http-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson-converter" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine-core" }
kakao-login = { group ="com.kakao.sdk", name="v2-user", version.ref="kakao" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref="glide" }
jodatime = { group = "joda-time", name = "joda-time", version.ref="jodatime"}
timber = { group="com.jakewharton.timber", name="timber", version.ref="timber"}
junit = { group = "junit", name="junit", version.ref="junit" }
junit-ext = { group = "androidx.test.ext", name="junit", version.ref="junit-ext" }
espresso = { group = "androidx.test.espresso", name="espresso-core", version.ref="espresso" }

[plugins]
application = { id = "com.android.application", version.ref = "application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-android" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
library = { id = "com.android.library", version.ref = "application" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-android" }
firebase-plugin = { id = "com.google.gms.google-services", version.ref = "firebase-plugin" }
gms-plugin = { id = "com.google.gms.google-services", version.ref = "firebase-plugin" }

[bundles]
android = ["androidCoreX", "androidCompat", "androidConstraint"]
network = ["retrofit", "http-logging", "gson-converter"]
